name: "pyFV3 translate tests"
on:
  push:
  pull_request:

jobs:
  fv3_translate_tests:
    uses: mlee03/pyFV3/.github/workflows/translate.yaml@reusing_workflows
    with:
      component_trigger:  true
      component_name: NDSL
