name: "SHiELD Translate tests"
on:
  push:
  pull_request:

jobs:
  shield_translate_tests:
    uses: mlee03/pySHiELD/.github/workflows/translate.yaml@reusing_workflows
    with:
      component_trigger:  true
      component_name: NDSL
